const categories = [
  "WEDDING",
  "CHRISTENING & NEWBORNS",
  "BIRTHDAY & PARTIES",
  "SEASONAL",
  "SCHOOL & TEACHER",
  "CORPORATE",
  "PERSONALISED",
  "NAMES, MONOGRAMS & TOPPERS",
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING",
  "INVITATIONS & DESIGN",
  "BALLOONS, SOAPS & CANDY CAKES",
  "CLOTHING, HATS & TOWELS"
];

const subcategories = {
  "WEDDING": ["HANGERS","WISH BOOKS","WEDDING SIGNS","WEDDING BOXES","TABLE NUMBERS & NAME TAGS","CAKE TOPPERS","WEDDING FAVOUR TAGS","WEDDING DECORATIONS"],
  "CHRISTENING & NEWBORNS": ["CHRISTENING HANGERS","WISH BOOKS & WISHES FRAMES","CHRISTENING BOXES","CHRISTENING TABLE DECOR","CHRISTENING INVITATIONS","BABY NAME DECORATIONS","NEWBORN BOXES & GIFTS","CHRISTENING SOAPS & BABY TOWELS"],
  "BIRTHDAY & PARTIES": ["CUSTOMISED BIRTHDAY GIFTS","DOOR HANGERS","KEYRINGS & MAGNETS","PHOTO FRAMES & NAME TAGS","SMALL BOXES & PENCIL CASES","PUZZLES, XO & TANGRAM GAMES","PARTY DECORATIONS & CAKE TOPPERS","INVITATIONS, CANDY CAKES & BALLOONS"],
  "SEASONAL": ["CHRISTMAS GIFTS","EASTER GIFTS","VALENTINE'S DAY","MOTHER'S DAY","FATHER'S DAY","WOMEN'S DAY","HALLOWEEN","NEW YEAR & OTHER SEASONAL GIFTS"],
  "SCHOOL & TEACHER": [
    "SCHOOL (1).jpg",
    "SCHOOL (10).jpg",
    "SCHOOL (11).jpg",
    "SCHOOL (12).jpg",
    "SCHOOL (13).jpg",
    "SCHOOL (14).jpg",
    "SCHOOL (15).jpg",
    "SCHOOL (16).jpg",
    "SCHOOL (5).jpg",
    "SCHOOL (6).jpg",
    "SCHOOL (7).jpg",
    "SCHOOL (8).jpg",
    "SCHOOL (9).jpg",
    "SCHOOL-(17).jpg",
    "SCHOOL-(18).jpg",
    "SCHOOL-19.jpg",
    "SCHOOL-20.jpg",
    "SCHOOL-21.jpg",
    "SCHOOL-22.jpg",
    "SCHOOL-23.jpg",
    "SCHOOL-24.jpg",
    "SCHOOL-25.jpg",
    "SCHOOL-26.jpg",
    "SCHOOL-27.jpg",
    "SCHOOL-28.jpg",
    "SCHOOL-29.jpg",
    "SCHOOL-30.jpg",
    "SCHOOL-31.jpg",
    "SCHOOL-32.jpg",
    "SCHOOL-33.jpg",
    "SCHOOL-34.jpg",
    "SCHOOL-36.jpg",
    "SCHOOL-38.jpg",
    "SCHOOL-40.jpg",
    "SCHOOL-41.jpg",
    "SCHOOL-50.jpg",
    "SCHOOL-71.jpg",
    "SCHOOL-75.jpg",
    "SCHOOL-77.jpg",
    "SCHOOL-78.jpg",
    "SCHOOL-82.jpg",
    "SCHOOL-84.jpg",
    "SCHOOL-85.jpg",
    "SCHOOL-87.jpg",
    "SCHOOL-88.jpg",
    "SCHOOL-91.jpg",
    "SCHOOL-92.jpg",
    "SCHOOL-93.jpg",
    "SCHOOL-94.jpg",
    "SCHOOL-95.jpg",
    "SCHOOL-96.jpg",
    "SCHOOL-97.jpg",
    "SCHOOL-98.jpg",
    "SCHOOL-99.jpg",
    "teacher1.jpg",
    "teacher2.jpg",
    "teacher3.jpg",
    "teacher4.jpg",
    "teacher6.jpg",
    "teacher7.jpg",
    "teacher8.jpg",
    "teacher9.jpg"
  ],
  "CORPORATE": [
    "CORPORATE (1).jpg",
    "CORPORATE (10).jpg",
    "CORPORATE (11).jpg",
    "CORPORATE (12).jpg",
    "CORPORATE (13).jpg",
    "CORPORATE (5).jpg",
    "CORPORATE (6).jpg",
    "CORPORATE (7).jpg",
    "CORPORATE (8).jpg",
    "CORPORATE-(14).jpg",
    "CORPORATE-15.jpg",
    "CORPORATE-16.jpg",
    "CORPORATE-17.jpg"
  ],
  "PERSONALISED": [
    "PERSONALISED (1).jpg",
    "PERSONALISED (1).png",
    "PERSONALISED (10).jpg",
    "PERSONALISED (11).jpg",
    "PERSONALISED (12).jpg",
    "PERSONALISED (13).jpg",
    "PERSONALISED (14).jpg",
    "PERSONALISED (15).jpg",
    "PERSONALISED (16).jpg",
    "PERSONALISED (17).jpg",
    "PERSONALISED (18).jpg",
    "PERSONALISED (19).jpg",
    "PERSONALISED (2).jpg",
    "PERSONALISED (20).jpg",
    "PERSONALISED (3).jpg",
    "PERSONALISED (4).jpg",
    "PERSONALISED (5).jpg",
    "PERSONALISED (7).jpg",
    "PERSONALISED (8).jpg",
    "PERSONALISED-(6).jpg",
    "PERSONALISED-(7).jpg",
    "PERSONALISED-10.jpg",
    "PERSONALISED-8.jpg",
    "PERSONALISED-9.jpg"
  ],
  "NAMES, MONOGRAMS & TOPPERS": ["NAMES (1).jpg","NAMES (2).jpg","NAMES (3).jpg","NAMES (4).jpg","NAMES (5).jpg","NAMES (6).jpg","NAMES (7).jpg","TOPPERS (1).jpg","TOPPERS (18).jpg","TOPPERS (19).jpg","TOPPERS (20).jpg","TOPPERS (21).jpg","TOPPERS (22).jpg","TOPPERS (23).jpg","TOPPERS (24).jpg","TOPPERS (25).jpg","TOPPERS (26).jpg","TOPPERS (27).jpg","TOPPERS (28).jpg","TOPPERS (29).jpg","TOPPERS (30).jpg","TOPPERS (31).jpg","TOPPERS (32).jpg","TOPPERS (33).jpg","TOPPERS (34).jpg","TOPPERS (35).jpg","TOPPERS (36).jpg"],
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING": [
    "CUSTOMISED FIGURES (1).jpg",
    "CUSTOMISED FIGURES (10).jpg",
    "CUSTOMISED FIGURES (11).jpg",
    "CUSTOMISED FIGURES (12).jpg",
    "CUSTOMISED FIGURES (13).jpg",
    "CUSTOMISED FIGURES (14).jpg",
    "CUSTOMISED FIGURES (15).jpg",
    "CUSTOMISED FIGURES (16).jpg",
    "CUSTOMISED FIGURES (17).jpg",
    "CUSTOMISED FIGURES (18).jpg",
    "CUSTOMISED FIGURES (19).jpg",
    "CUSTOMISED FIGURES (2).jpg",
    "CUSTOMISED FIGURES (20).jpg",
    "CUSTOMISED FIGURES (21).jpg",
    "CUSTOMISED FIGURES (22).jpg",
    "CUSTOMISED FIGURES (23).jpg",
    "CUSTOMISED FIGURES (24).jpg",
    "CUSTOMISED FIGURES (25).jpg",
    "CUSTOMISED FIGURES (26).jpg",
    "CUSTOMISED FIGURES (27).jpg",
    "CUSTOMISED FIGURES (28).jpg",
    "CUSTOMISED FIGURES (29).jpg",
    "CUSTOMISED FIGURES (3).jpg",
    "CUSTOMISED FIGURES (30).jpg",
    "CUSTOMISED FIGURES (31).jpg",
    "CUSTOMISED FIGURES (32).jpg",
    "CUSTOMISED FIGURES (33).jpg",
    "CUSTOMISED FIGURES (34).jpg",
    "CUSTOMISED FIGURES (35).jpg",
    "CUSTOMISED FIGURES (36).jpg",
    "CUSTOMISED FIGURES (37).jpg",
    "CUSTOMISED FIGURES (38).jpg",
    "CUSTOMISED FIGURES (39).jpg",
    "CUSTOMISED FIGURES (4).jpg",
    "CUSTOMISED FIGURES (40).jpg",
    "CUSTOMISED FIGURES (41).jpg",
    "CUSTOMISED FIGURES (42).jpg",
    "CUSTOMISED FIGURES (43).jpg",
    "CUSTOMISED FIGURES (44).jpg",
    "CUSTOMISED FIGURES (45).jpg",
    "CUSTOMISED FIGURES (46).jpg",
    "CUSTOMISED FIGURES (47).jpg",
    "CUSTOMISED FIGURES (48).jpg",
    "CUSTOMISED FIGURES (49).jpg",
    "CUSTOMISED FIGURES (5).jpg",
    "CUSTOMISED FIGURES (50).jpg",
    "CUSTOMISED FIGURES (6).jpg",
    "CUSTOMISED FIGURES (7).jpg",
    "CUSTOMISED FIGURES (8).jpg",
    "CUSTOMISED FIGURES (9).jpg",
    "ENGRAVING.jpg",
    "foamboards (1).jpg",
    "foamboards (2).jpg",
    "foamboards (3).jpg"
  ],
  "INVITATIONS & DESIGN": [
    "INVITATIONS (1).jpg",
    "INVITATIONS (10).jpg",
    "INVITATIONS (11).jpg",
    "INVITATIONS (12).jpg",
    "INVITATIONS (13).jpg",
    "INVITATIONS (14).jpg",
    "INVITATIONS (15).jpg",
    "INVITATIONS (16).jpg",
    "INVITATIONS (17).jpg",
    "INVITATIONS (18).jpg",
    "INVITATIONS (19).jpg",
    "INVITATIONS (2).jpg",
    "INVITATIONS (20).jpg",
    "INVITATIONS (21).jpg",
    "INVITATIONS (22).jpg",
    "INVITATIONS (23).jpg",
    "INVITATIONS (24).jpg",
    "INVITATIONS (25).jpg",
    "INVITATIONS (26).jpg",
    "INVITATIONS (27).jpg",
    "INVITATIONS (28).jpg",
    "INVITATIONS (29).jpg",
    "INVITATIONS (3).jpg",
    "INVITATIONS (30).jpg",
    "INVITATIONS (31).jpg",
    "INVITATIONS (32).jpg",
    "INVITATIONS (33).jpg",
    "INVITATIONS (34).jpg",
    "INVITATIONS (35).jpg",
    "INVITATIONS (36).jpg",
    "INVITATIONS (37).jpg",
    "INVITATIONS (38).jpg",
    "INVITATIONS (39).jpg",
    "INVITATIONS (4).jpg",
    "INVITATIONS (40).jpg",
    "INVITATIONS (41).jpg",
    "INVITATIONS (42).jpg",
    "INVITATIONS (43).jpg",
    "INVITATIONS (44).jpg",
    "INVITATIONS (45).jpg",
    "INVITATIONS (46).jpg",
    "INVITATIONS (47).jpg",
    "INVITATIONS (5).jpg",
    "INVITATIONS (6).jpg",
    "INVITATIONS (7).jpg",
    "INVITATIONS (8).jpg",
    "INVITATIONS (9).jpg"
  ],
  "BALLOONS, SOAPS & CANDY CAKES": [
    "ballons (10).jpg",
    "ballons (3).jpg",
    "ballons (4).jpg",
    "ballons (5).jpg",
    "ballons (6).jpg",
    "ballons (7).jpg",
    "ballons (8).jpg",
    "ballons (9).jpg",
    "ballons-11.jpg",
    "ballons-12.jpg",
    "soaps (10).jpg",
    "soaps (11).jpg",
    "soaps (5).jpg",
    "soaps (6).jpg",
    "soaps (7).jpg",
    "soaps (8).jpg",
    "soaps (9).jpg"
  ],
  "CLOTHING, HATS & TOWELS": [
    "CLOTHING (1).jpg",
    "CLOTHING (3).jpg",
    "CLOTHING (5).jpg",
    "CLOTHING-10.jpg",
    "CLOTHING-11.jpg",
    "CLOTHING-12.jpg",
    "CLOTHING-13.jpg",
    "CLOTHING-14.jpg",
    "CLOTHING-15.jpg",
    "CLOTHING-16.jpg",
    "CLOTHING-17.jpg",
    "CLOTHING-18.jpg",
    "CLOTHING-19.jpg",
    "CLOTHING-20.jpg",
    "CLOTHING-21.jpg"
  ]
};

const products = [];
