const categories = [
  "WEDDING",
  "CHRISTENING & NEWBORNS",
  "BIRTHDAY & PARTIES",
  "SEASONAL",
  "SCHOOL & TEACHER GIFTS",
  "CORPORATE GIFTS",
  "PERSONALISED GIFTS",
  "NAMES, MONOGRAMS & TOPPERS",
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING",
  "INVITATIONS & DESIGN",
  "BALLOONS, SOAPS & CANDY CAKES",
  "CLOTHING & TOWELS"
];

const subcategories = {
  "CHRISTENING & NEWBORNS": ["HANGERS","WISH BOOKS","WISHES FRAMES","CHRISTENING BOXES","CHRISTENING TABLE DECOR","CHRISTENING ACCESSORIES","CHRISTENING INVITATIONS","NEWBORN BOXES","BABY NAME DECORATIONS","BABY TOWELS","NEWBORN CAKE TOPPERS","CHRISTENING SOAPS"],
  "NAMES, MONOGRAMS & TOPPERS": ["NAMES","MONOGRAMS","CAKE TOPPERS","FLOWER TOPPERS","NAME & AGE TOPPERS","CUSTOMISED TOPPERS","TABLE DECOR","CUSTOMISED DECORATIONS"],
  "WEDDING": ["HANGERS","WISH BOOKS","WEDDING SIGNS","WEDDING BOXES","WEDDING TABLE DECOR","WEDDING ACCESSORIES","WEDDING GIFTS","WEDDING INVITATIONS"],
  "BIRTHDAY & PARTIES": ["BIRTHDAY GIFTS","PHOTO FRAMES","CANDY CAKES","BIRTHDAY INVITATIONS","PARTY FAVOURS","PARTY DECORATIONS"],
  "SEASONAL": ["CHRISTMAS","EASTER","VALENTINE'S DAY","MOTHER'S DAY","FATHER'S DAY","WOMEN'S DAY","HALLOWEEN","NEW YEAR","OTHER SEASONAL GIFTS"],
  "PERSONALISED GIFTS": ["KEYCHAINS","PHOTO FRAMES","PERSONALISED BOXES","ENGRAVED GIFTS","PIGGY BANKS","PENCIL CASES","SCHOOL GIFTS","DOOR HANGERS","MAGNETS","COASTERS","CUSTOMISED GIFTS"],
  "SCHOOL & TEACHER GIFTS": ["BACK TO SCHOOL","END OF SCHOOL","TEACHER GIFTS","EDUCATIONAL GIFTS","SCHOOL ACCESSORIES","CHRISTMAS GIFTS","EASTER GIFTS"],
  "CORPORATE GIFTS": ["CORPORATE BOXES","WINE BOXES","COASTERS","NAME TAGS","CORPORATE SIGNS","LOGO ENGRAVING","CORPORATE GIFTS","PROMOTIONAL GIFTS","CORPORATE EVENT GIFTS"],
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING": ["CUSTOMISED FIGURES","CUSTOMISED CUT OUTS","MUGS","THUMBLERS","WOOD ENGRAVING","ACRYLIC ENGRAVING","LEATHER ENGRAVING","GLASS ENGRAVING","METAL ENGRAVING WITH COLOUR COATING","CUSTOM ENGRAVING"],
  "INVITATIONS & DESIGN": ["CHRISTENING INVITATIONS","WEDDING INVITATIONS","BIRTHDAY INVITATIONS","PARTY INVITATIONS","SCHOOL INVITATIONS","SEASONAL INVITATIONS","LOGO DESIGN","FLYER DESIGN","BUSINESS CARD DESIGN","INVITATION DESIGN","BROCHURE DESIGN","POSTER DESIGN","MENU DESIGN","SOCIAL MEDIA DESIGN","LABELS & STICKERS","PACKAGING DESIGN","CUSTOM GRAPHIC DESIGN"],
  "BALLOONS, SOAPS & CANDY CAKES": ["BUBBLE BALLOONS","PERSONALISED SOAPS","CANDY CAKES","CANDY BOUQUETS","PERSONALISED BALLOON GIFTS"],
  "CLOTHING & TOWELS": ["T-SHIRTS","HOODIES","HATS","PERSONALISED CLOTHING","TOWELS","BABY TOWELS","EMBROIDERED TOWELS","CUSTOM CLOTHING & TEXTILES"]
};

const featuredProducts = {};

const mainCategoryPhotos = {
  "CHRISTENING & NEWBORNS": "CHRISTENING (2).jpg",
  "NAMES, MONOGRAMS & TOPPERS": "TOPPERS (2).jpg",
  "WEDDING": "WEDDING (1).jpg",
  "BIRTHDAY & PARTIES": "BIRTHDAY (6).jpg",
  "SEASONAL": "MOTHERS (10).jpg",
  "PERSONALISED GIFTS": "PERSONALISED (6).jpg",
  "SCHOOL & TEACHER GIFTS": "SCHOOL (11).jpg",
  "CORPORATE GIFTS": "CORPORATE (8).jpg",
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING": "",
  "INVITATIONS & DESIGN": "INVITATION (44).jpg",
  "BALLOONS, SOAPS & CANDY CAKES": "",
  "CLOTHING & TOWELS": ""
};

const products = [];
