const categories = [
  "WEDDING",
  "CHRISTENING & NEWBORNS",
  "BIRTHDAY & PARTIES",
  "SEASONAL",
  "SCHOOL & TEACHER",
  "CORPORATE",
  "PERSONALISED",
  "NAMES, MONOGRAMS & TOPPERS",
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING",
  "INVITATIONS & DESIGN",
  "BALLOONS, SOAPS & CANDY CAKES",
  "CLOTHING, HATS & TOWELS"
];

const subcategories = {
  "WEDDING": ["HANGERS","WISH BOOKS","WEDDING SIGNS","WEDDING BOXES","TABLE NUMBERS & NAME TAGS","CAKE TOPPERS","WEDDING FAVOUR TAGS","WEDDING DECORATIONS"],
  "CHRISTENING & NEWBORNS": ["CHRISTENING HANGERS","WISH BOOKS & WISHES FRAMES","CHRISTENING BOXES","CHRISTENING TABLE DECOR","CHRISTENING INVITATIONS","BABY NAME DECORATIONS","NEWBORN BOXES & GIFTS","CHRISTENING SOAPS & BABY TOWELS"],
  "BIRTHDAY & PARTIES": ["CUSTOMISED BIRTHDAY GIFTS","DOOR HANGERS","KEYRINGS & MAGNETS","PHOTO FRAMES & NAME TAGS","SMALL BOXES & PENCIL CASES","PUZZLES, XO & TANGRAM GAMES","PARTY DECORATIONS & CAKE TOPPERS","INVITATIONS, CANDY CAKES & BALLOONS"],
  "SEASONAL": ["CHRISTMAS GIFTS","EASTER GIFTS","VALENTINE'S DAY","MOTHER'S DAY","FATHER'S DAY","WOMEN'S DAY","HALLOWEEN","NEW YEAR & OTHER SEASONAL GIFTS"],
  "SCHOOL & TEACHER": ["BACK TO SCHOOL","SCHOOL ACCESSORIES","PENCIL CASES & RULERS","EDUCATIONAL GIFTS","TEACHER GIFTS","END OF SCHOOL GIFTS","SCHOOL CHRISTMAS GIFTS","SCHOOL EASTER GIFTS"],
  "CORPORATE": ["CORPORATE BOXES","WINE BOXES","COASTERS","NAME TAGS","CORPORATE SIGNS","LOGO ENGRAVING","CORPORATE GIFTS","PROMOTIONAL & EVENT GIFTS"],
  "PERSONALISED": ["KEYRINGS, MAGNETS & COASTERS","PHOTO FRAMES, NAME TAGS & NAME PLATES","PERSONALISED BOXES, PENCIL CASES & DIARIES","PIGGY BANKS & SCHOOL GIFTS","DOOR HANGERS & ACRYLIC DOOR NUMBERS","SIGNS, MIRRORS & DECORATIONS","SAINTS & CUSTOM ORNAMENTS","CUSTOMISED GIFTS & CUT OUTS"],
  "NAMES, MONOGRAMS & TOPPERS": ["CUSTOM NAMES","MONOGRAMS","CAKE TOPPERS","FLOWER TOPPERS","NAME & AGE TOPPERS","CUSTOMISED TOPPERS","TABLE DECOR","CUSTOMISED DECORATIONS"],
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING": [
    "CUSTOM COLOR FIGURES",
    "CUSTOM CUT OUTS",
    "WOOD & ACRYLIC CUT OUTS",
    "CUSTOM SIGNS",
    "LASER ENGRAVING",
    "COLOR-COATED THUMBLER ENGRAVING",
    "LEATHER CUT OUT & ENGRAVING",
    "FOAMBOARDS"
  ],
  "INVITATIONS & DESIGN": ["CHRISTENING INVITATIONS","WEDDING INVITATIONS","BIRTHDAY & PARTY INVITATIONS","SCHOOL & SEASONAL INVITATIONS","LOGO & BRANDING DESIGN","FLYERS, BUSINESS CARDS & BROCHURES","MENUS, POSTERS & SOCIAL MEDIA DESIGN","LABELS, STICKERS & PACKAGING DESIGN"],
  "BALLOONS, SOAPS & CANDY CAKES": [
    "STUFFED BUBBLE BALLOONS",
    "PERSONALISED SOAPS",
    "CANDY CAKES",
    "CUSTOM GIFT SETS"
  ],
  "CLOTHING, HATS & TOWELS": [
    "T-SHIRTS",
    "HOODIES",
    "HATS",
    "PERSONALISED CLOTHING",
    "TOWELS",
    "BABY TOWELS",
    "EMBROIDERED & PRINTING",
    "CUSTOM CLOTHING & TEXTILES"
  ]
};

const featuredProducts = {};

const mainCategoryPhotos = {
  "WEDDING": "WEDDING (1).jpg",
  "CHRISTENING & NEWBORNS": "CHRISTENING (2).jpg",
  "BIRTHDAY & PARTIES": "BIRTHDAY (6).jpg",
  "SEASONAL": "CHRISTMAS (10).jpg",
  "SCHOOL & TEACHER": "SCHOOL (11).jpg",
  "CORPORATE": "CORPORATE (8).jpg",
  "PERSONALISED": "PERSONALISED-(6).jpg",
  "NAMES, MONOGRAMS & TOPPERS": "NAMES (1).jpg",
  "CUSTOMISED FIGURES, CUT OUTS & LASER ENGRAVING": "CUSTOMISED FIGURES (32).jpg",
  "INVITATIONS & DESIGN": "INVITATIONS (17).jpg",
  "BALLOONS, SOAPS & CANDY CAKES": "soaps (7).jpg",
  "CLOTHING, HATS & TOWELS": "CLOTHING-15.jpg"
};

const products = [];
